### ISSUE TITLE
We need walktrough on how to install/use contribute to this

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#1]

**Comment by NardJ** [comment]
I have added it to the README.md.  I have just finished implementing editing of all data field in the Photon file. The GUI is not very pretty at this moment, but it works well enough. The next functionality to implement will probably be importing/replacing of bitmap data. Any feedback of any kind is more than welcome!

**Comment by NardJ** [comment]
Another thing: there are a number of data-fields in the Photon file for which I do not know the usage (neither is it available in the [010-template](https%3A%2F%2Fgithub.com%2FaltLab%2Fphoton-resin-calibration%2Fblob%2Fmaster%2F010editor-template%2Fanycubic-photon-hextemplate.bt)). Any more info about these fields would help me!

**Comment by X3msnake** [comment]
@NardJ does this help?

https://github.com/Reonarudo/pcb2photon/issues/2

**Comment by X3msnake** [comment]
@NardJ Excelent work with the walk-through i'll be testing it this weekend and will post back ;)

**Comment by NardJ** [comment]
That helped, I now have previews available!
