### ISSUE TITLE
Wrong image size crash were a popup warning should exist!

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#15]
![image](https://user-images.githubusercontent.com/11083514/41692434-34a37114-74f8-11e8-8efc-e2ee541944b7.png)

The software should not exit if it enconters a error. Doing this means the user will lose all changes he has done to the file.

In this particular case a error message should be displayed and the command ignored returning to the program menu.

**Comment by NardJ** [comment]
@X3msnake Solved in branch New-features.
