### ISSUE TITLE
Creating new file crashes program

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#16]
![image](https://user-images.githubusercontent.com/11083514/41692932-cdd1c6fe-74fa-11e8-8e17-d5e67d04b1f6.png)

**Comment by X3msnake** [comment]
Fixed issue added template file to resources folder
also changed the colour of background to relate to the UV exposure light from the machine (What user sees when looking at machine without the vat and resin) Helps user to better understand what gets exposed and what does not get exposed

![image](https://user-images.githubusercontent.com/11083514/41695948-651c6d80-7509-11e8-9095-81b1959eaaf5.png)
![image](https://user-images.githubusercontent.com/11083514/41695957-74c0e4f0-7509-11e8-9be5-382ac51c9fe2.png)

**Comment by X3msnake** [comment]
![image](https://user-images.githubusercontent.com/11083514/41696790-cf256354-750d-11e8-894e-39c49f25dfc2.png)
![image](https://user-images.githubusercontent.com/11083514/41696794-d3233e04-750d-11e8-9334-9bd339e39537.png)
![image](https://user-images.githubusercontent.com/11083514/41696798-d6d7ee0a-750d-11e8-8f2c-a67a34f7803d.png)

**Comment by NardJ** [comment]
Great! Since I'm new to github: as I understand you made the changes to the master. Meanwhile the other branch was also editor. How do I pull these together... or does github do this automatically when I choose merge?
