### ISSUE TITLE
Replace and Export bitmap crashes if no file is loaded!

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#17]
![image](https://user-images.githubusercontent.com/11083514/41692961-fe0068bc-74fa-11e8-853d-f72f1a8f66dc.png)

Should instead popup a message like import bitmap and save as does

![image](https://user-images.githubusercontent.com/11083514/41693009-3b4bdba2-74fb-11e8-9c30-29f72dfebd8c.png)

**Comment by NardJ** [comment]
Solved in branch New-features.
![image](https://user-images.githubusercontent.com/11459480/41798372-b82defa2-766d-11e8-816f-f2399e7e5704.png)
