### ISSUE TITLE
Delete current layer

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#18]
Allow user to delete the layer he is looking at.

we should in a near future implement a undo #19  as alternative we can instead of deleting the layer just allow the user to mark the layer for deletion, and must hit commit so that the layer deletion are processed.

I think this last idea make more sense it would look something like this

![image](https://user-images.githubusercontent.com/11083514/41693597-f6757404-74fd-11e8-8910-2dd2ec8259ff.png)

I feel this last idea can be improved with some debate.

**Comment by NardJ** [comment]
Added functionality. Will have to think about GUI changes for cut/copy/past/duplicate.

**Comment by NardJ** [comment]
Done in new-features branch
