### ISSUE TITLE
PhotonViewer - No such file

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#2]
I believe you want ot say in the instructions PhotonEditor.py?

![image](https://user-images.githubusercontent.com/11083514/41510679-e9917408-7260-11e8-9332-e50fd852f690.png)

**Comment by NardJ** [comment]
You are absolutely right. I think you downloaded the files while I was editing Readme.md. The instructions now read 'PhotonEditor.py'

**Comment by X3msnake** [comment]
cool
