### ISSUE TITLE
Disclaimer - Use at own risk

### ISSUE THREAD

**Issue by NardJ** [NardJ/PhotonFileUtils#42]
Yesterdag I found a bug in the New-features branch which generated layers at a lower position than the previous layer. This could make the Photon drive it resin-model back into the LCD display. 
Because of this I think it would be good to add an disclaimer to the project. What do you think?

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by X3msnake** [comment]
That's already in the License File you chose for the project no?

![image](https://user-images.githubusercontent.com/11083514/41910540-e0e018ea-7941-11e8-8954-8bf3557b5005.png)

**Comment by X3msnake** [comment]
But I think it is more important to warn users inside the software that they should do a dry run of the files generated with PFU

Maybe a "nag screen" on first boot of the program that you must click ok

something like
"
Reminder
- Use this at your own risk
- Backup your photon files before using the software
- Verify and dry test your files before doing a production run
"
And a checkbox to remove the nag screen
"I understand the risks stop nagging me"

**Comment by NardJ** [comment]
Well a nag-screen is possible, however another (easier) option (to implement) is. Does this suffice?
![image](https://user-images.githubusercontent.com/11459480/42127491-0f9cb6c4-7c9a-11e8-8a33-bc9043f0b9ee.png)

**Comment by X3msnake** [comment]
@NardJ This is a elegant and unintrusive solution Master, well done :)

**Comment by NardJ** [comment]
Thx, I am also thinking about checking availability of Numpy and OpenGL and if absent a reminder to install them
