### ISSUE TITLE
Sugestion - Add build date to version about

### ISSUE THREAD

**Issue by X3msnake** [NardJ/PhotonFileUtils#53]
![image](https://user-images.githubusercontent.com/11083514/42065364-736c9ade-7b32-11e8-86a3-aebe5a3fe5d8.png)

Something like 

Version Alpha 20180629 

date being the last commit date

**Comment by NardJ** [comment]
Added, the version string from the file PhotonEditor.py will be used in the about box. New file PhotonEditor.py will be uploaded to Fixes-and-Features.

![image](https://user-images.githubusercontent.com/11459480/42127243-e111ea2c-7c94-11e8-90a6-7898072a6ca9.png)
